### ISSUE TITLE
Home Page - Completion Checklist

### ISSUE THREAD

**Issue by Ormatist** [The-Iceburg/blgc#1]
- [ ]  News and Events tabs not spanning correct width close to the breakpoint
- [ ] Re-design the contact form (behind the scenes) to ensure responsive
- [ ] Design footer
- [ ] Make footer responsive
- [ ] Ensure all buttons have appropriate links
- [ ] make the hamburger dropdown work
- [ ] add dropdowns to make nav tabs?
- [ ] write some theoretical php for the contact form
